import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'
import ConvexClientProvider from "@/app/ConvexClientProvider";
import {Header} from "@/app/header";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className={'w-screen h-auto bg-gradient-to-b from-blue-50 to-red-100'}>
          <ConvexClientProvider>
            <div className={'min-h-[calc(100vh-4rem)]'}>
              <Header/>
              {children}
              <Toaster/>
            </div>
          </ConvexClientProvider>
        </div>
      </body>
    </html>
  );
}
